version: "3.8"

services:
  mariadb:
    restart: always
    image: mariadb:10.7.4
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mariadb:/var/lib/mysql
    network_mode: host
  rabbitmq:
    restart: always
    image: rabbitmq:3.9.21-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 384M
  fast-download:
    restart: always
    image: af0x/rehlds-fastdl
    volumes:
      - ./resources:/static
    network_mode: host
  cs:
    restart: always
    profiles:
      - all
      - cs
    depends_on:
      - rabbitmq
    image: af0x/hlds-agent:cs-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27015
      MAP: de_dust2_2x2
      GAME_TYPE: cs-classic
    volumes:
      - ./docker/cs/maps.ini:/hlds/cstrike/addons/amxmodx/configs/maps.ini
      - ./docker/cs/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/cs/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
  csdm:
    restart: always
    profiles:
      - all
      - csdm
    depends_on:
      - rabbitmq
    image: af0x/hlds-agent:csdm-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27017
      MAP: de_dust2_2x2
      GAME_TYPE: cs-dm
    volumes:
      - ./docker/csdm/maps.ini:/hlds/cstrike/addons/amxmodx/configs/maps.ini
      - ./docker/csdm/server.cfg:/hlds/cstrike/server.cfg
      - ./docker/csdm/maps:/hlds/cstrike/maps
      - ./docker/users.ini:/hlds/cstrike/addons/amxmodx/configs/users.ini
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
  half-life:
    restart: always
    profiles:
      - all
      - hl
    depends_on:
      - rabbitmq
    image: af0x/hlds-agent:hl-nosteam
    environment:
      RCON_PASSWORD: ${RCON_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      PORT: 27016
      MAP: 1337_Street
      GAME_TYPE: half-life

    volumes:
      - ./docker/half-life/maps.ini:/hlds/valve/addons/amxmodx/configs/maps.ini
      - ./docker/half-life/server.cfg:/hlds/valve/server.cfg
      - ./docker/half-life/maps:/hlds/valve/maps
      - ./docker/users.ini:/hlds/valve/addons/amxmodx/configs/users.ini
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 512M
